### ISSUE TITLE
Extraction fails under Windows

### ISSUE THREAD

**Issue by provegard** [localytics/sbt-dynamodb#19]
The original plugin never worked well under Windows, so we're used to having to extract the tar.gz file manually and then rerunning the tests. But with this plugin, we get a failure even if the tar.gz file has been extracted manually:

```
[info] Extracting file: [C:\...\dynamodb-local\dynamodb_local_2016-01-07_1.0.tar.gz]
tar (child): Cannot connect to C: resolve failed

gzip: stdin: unexpected end of file
tar: Child returned status 128
tar: Error is not recoverable: exiting now
java.lang.RuntimeException: Nonzero exit value: 2
        at scala.sys.package$.error(package.scala:27)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.slurp(ProcessBuilderImpl.scala:131)
        at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang$bang(ProcessBuilderImpl.scala:101)
        at com.localytics.sbt.dynamodb.DynamoDBLocalTasks$$anonfun$deployDynamoDBLocalTask$1.apply(DynamoDBLocalTasks.scala:28)
        at com.localytics.sbt.dynamodb.DynamoDBLocalTasks$$anonfun$deployDynamoDBLocalTask$1.apply(DynamoDBLocalTasks.scala:13)
        at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:35)
        at scala.Function5$$anonfun$tupled$1.apply(Function5.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

This is the result of running under Git Bash, by the way. Converting the path to something like "/c/..." makes tar happy, but I guess the most portable way is probably to run the tar command in the folder where the tar.gz file is and use a relative path.

Related question: If the tar.gz file has been extracted already, wouldn't it make sense to just skip the extraction?

**Comment by bdarfler** [comment]
Hi @provegard sorry for the very slow response! I wasn't set up as a watcher for this repo and missed your issue.

I completely agree that we shouldn't have to extract the tar.gz file if its already been extracted. I have fixed that in https://github.com/localytics/sbt-dynamodb/pull/21 and release [v1.4.2](https://bintray.com/localytics/sbt-plugins/sbt-dynamodb/1.4.2).

I'm going to close this issue but if you feel that this is not adequate please let us know. 

I would love to make this project more Windows friendly but unfortunately, I don't have easy access to a Windows environment or have much experience with the platform. Please consider submitting a Windows support PR if you have the time. I'd be happy to help in any way I can.

**Comment by brentax** [comment]
I just ran into this problem as well. On Windows, the absolute file path includes a colon `:`, which tells `tar` to look for the file remotely ([found here](http://unix.stackexchange.com/questions/13377/tar-extraction-depends-on-filename/13381#13381)). We should be able to add the `--force-local` option to the tar command in order to fix this.

I'm happy to open a PR if you'd like.

**Comment by bdarfler** [comment]
@brentax I'd love a PR for this. I can test it on Mac if you are able to test on Windows. I do an `sbt publish-local` and then make use of it in another project to verify.
