### ISSUE TITLE
the link to download dynamo_local jar seems to be down

### ISSUE THREAD

**Issue by harshith-c** [localytics/sbt-dynamodb#32]
When I run the tests through sbt I keep getting (these tests used to work until recently) :

info] Downloading targz from [http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz] to [/Users/hchennamaneni/hiya/identity-data-service-common/dynamodb-local/dynamodb_local_latest.tar.gz]
Exception in thread "Thread-54" java.io.FileNotFoundException: http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
..

Trying the link in a browser returns 404 Not Found. Has this file been moved or taken offline?

**Comment by bdarfler** [comment]
Fixed by https://github.com/localytics/sbt-dynamodb/pull/30. Please update to `v1.5.3`
